name: 'Terraform Plan and Apply'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Save Plan Output
      id: save_plan
      run: echo "PLAN_OUTPUT=$(terraform show -json tfplan)" >> $GITHUB_ENV

    - name: Add Plan Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const planOutput = process.env.PLAN_OUTPUT;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `#### Terraform Plan Output\n\`\`\`json\n${planOutput}\n\`\`\``
          });

    - name: Apply Terraform
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve tfplan
