name: 'Terraform'

on:
  push:
    branches: [ "main" ]

permissions: 
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configure Azure credentials
      run: |
        echo "AZURE_STORAGE_SAS_TOKEN=${{ secrets.AZURE_STORAGE_SAS_TOKEN }}" >> $GITHUB_ENV

    - name: Create tfvars file
      run: |
       echo "${{ secrets.TF_VARS }}" > terraform.tfvars
       
    - name: Debug tfvars file
      run: cat terraform.tfvars
      
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var-file="terraform.tfvars"

    - name: Save Plan State
      id: save_plan_state
      run: echo "PLAN_OUTPUT=$(terraform show -json tfplan)" >> $GITHUB_STATE

    - name: Save Plan Output
      id: save_plan_output
      run: echo "PLAN_OUTPUT=$(terraform show -json tfplan)" >> $GITHUB_OUTPUT

    - name: Add Plan Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const planOutput = process.env.PLAN_OUTPUT;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `#### Terraform Plan Output\n\`\`\`json\n${planOutput}\n\`\`\``
          });

    - name: Terraform Apply
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve tfplan -var-file="terraform.tfvars"
