name: 'Terraform Plan, Apply, and Destroy'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Run destroy stage'
        required: true
        default: 'false'

jobs:
  TF_PLAN:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Decode .tfvars from GitHub secret
      run: |
        echo "${{ secrets.TFVARS_B64 }}" | base64 --decode > variables-de.tfvars
        echo "Decoded variables-de.tfvars file."

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="variables-de.tfvars"

  TF_APPLY:
    runs-on: ubuntu-latest
    needs: TF_PLAN
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Decode .tfvars from GitHub secret
      run: |
        echo "${{ secrets.TFVARS_B64 }}" | base64 --decode > variables-de.tfvars
        echo "Decoded variables-de.tfvars file."

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -var-file="variables-de.tfvars" -auto-approve

  TF_DESTROY:
    runs-on: ubuntu-latest
    needs: TF_PLAN
    if: github.event.inputs.destroy == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Decode .tfvars from GitHub secret
      run: |
        echo "${{ secrets.TFVARS_B64 }}" | base64 --decode > variables-de.tfvars
        echo "Decoded variables-de.tfvars file."

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy Terraform
      run: terraform destroy -var-file="variables-de.tfvars" -auto-approve
