name: 'Terraform Plan and Apply'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Decode .tfvars from GitHub secret
      run: |
        echo "${{ secrets.TFVARS_B64 }}" | base64 --decode > variables-de.tfvars
        echo "Decoded variables-de.tfvars file."

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var-file="variables-de.tfvars"

    - name: Save Plan State
      id: save_plan_state
      run: echo "PLAN_OUTPUT=$(terraform show -json tfplan)" >> $GITHUB_STATE
      
    - name: Apply Terraform
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve tfplan -var-file="variables-de.tfvars"
